### ISSUE TITLE
Basic test fails: Candidate not found

### ISSUE THREAD

**Issue by lizmat** [ugexe/Perl6-CompUnit--Repository--Tar#1]
$ perl6 -Ilib t/01-require-path.t 
1..2
    ok 1 - module not yet loaded
    ok 2 - module require-d ok
    not ok 3 - module is accessable
    # Failed test 'module is accessable'
    # at t/01-require-path.t line 12
    1..3
    # Looks like you failed 1 test of 3
not ok 1 - require module with no dependencies
# Failed test 'require module with no dependencies'
# at t/01-require-path.t line 9
    ok 1 - module not yet loaded
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol 'Candidate'
  in block <unit> at t/01-require-path.t line 12

    ok 2 - module require-d ok
    not ok 3 - module loaded
    # Failed test 'module loaded'
    # at t/01-require-path.t line 18
    1..3
    # Looks like you failed 1 test of 3
not ok 2 - require modules with multi-level dependency chain
# Failed test 'require modules with multi-level dependency chain'
# at t/01-require-path.t line 15
# Looks like you failed 2 tests of 2

**Comment by ugexe** [comment]
Failures have been resolved
